network = "testnet"

[datastore_config]
type = "GCS"

[datastore_config.params]
destination_bucket_path = "exporter-test/ledgers"

[exporter_config]
  ledgers_per_file = 1
  files_per_partition = 64000
  file_suffix = ".xdr.gz"

[hcnet_core_config]
  hcnet_core_binary_path = "/usr/local/bin/hcnet-core"

